### obtener todos los deportes
GET http://localhost:3000/api/deportes


### obtener un deporte
GET http://localhost:3000/api/deportes/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo deporte
POST http://localhost:3000/api/deportes
Content-Type: application/json

{
  "tipo": "Futbol",
  "cupo": 30,
  "horario": [{"dia": "Martes", "hora_inicio": "11:00"}],
  "costo": 9000
}


### modificar un deporte (PUT - recurso completo e idempotente)
//PUT http://localhost:3000/api/deportes/a02b91bc-3769-4221-beb1-d7a3aeba7dad
//Content-Type: application/json
//{
//   "tipo": "Natacion",
//  "cupo": 12,
//  "horario": [{"dia": "Lunes", "hora_inicio": "9:00"}],
//  "costo": 10000 
//} 

curl -X PUT http://localhost:3000/api/deportes/a02b91bc-3769-4221-beb1-d7a3aeba7dad \
-H "Content-Type: application/json" \
-d '{
   "tipo": "Natacion",
   "cupo": 12,
   "horario": [{"dia": "Lunes", "hora_inicio": "9:00"}],
   "costo": 10000 
}'

 

### modificar un deporte (PATCH - recurso parcial)
PATCH http://localhost:3000/api/deportes/a02b91bc-3769-4221-beb1-d7a3aeba7dad
 

### borrar un deporte
DELETE http://localhost:3000/api/deportes/a02b91bc-3769-4221-beb1-d7a3aeba7dad

